version: '3.5'

services:
  crossdb:
    image: mongo
    ports:
      - "27021:27017"
    networks:
      - proxynet
  crossweb:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8004:8000"
    depends_on:
      - crossdb
    networks:
      - proxynet
    environment:
      - COVERALLS_REPO_TOKEN

networks:
  proxynet:
    name: GamesBI-network
